# Generated by Django 6.0.3 on 2026-05-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
