# Generated by Django 6.0.3 on 2026-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_peca_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
