# Generated by Django 6.0.3 on 2026-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_ordemservico_data_conclusao_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
