# Generated by Django 6.0.3 on 2026-05-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_veiculo'),
        ('ordens', '0003_ordemservico_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo'),
        ),
    ]
