# Generated by Django 6.0.3 on 2026-05-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_veiculo_options_remove_veiculo_data_cadastro_and_more'),
        ('ordens', '0004_ordemservico_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='concluida',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.veiculo'),
        ),
    ]
