# Generated by Django 6.0.5 on 2026-05-08 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_funcionario'),
        ('ordens', '0005_remove_ordemservico_concluida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.funcionario'),
        ),
    ]
