# Generated by Django 6.0.3 on 2026-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
